name: Release

on:
  push:
    branches: [ "main" ]
    paths:
      - 'url.txt'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Parse
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./scripts/download.sh
          yarn install
          node scripts/release.js
